### ISSUE TITLE
Multi languages

### ISSUE THREAD

**Issue by Bashamega** [mariocraft987/bark-coding#180]
Hello:)
What about if we add the available languages in the footer or settings?
I can do both

**Comment by mariocraft987** [comment]
Yes, please go to `src/translations`

**Comment by Bashamega** [comment]
> Yes, please go to `src/translations`

Would you prefer them in the footer or settings?

**Comment by qwertyy-dev** [comment]
> > Yes, please go to `src/translations`
> 
> Would you prefer them in the footer or settings?

i vote both

**Comment by mariocraft987** [comment]
settings

**Comment by Bashamega** [comment]
Please decide @qwertyy-dev @mariocraft987 @BwnnyRxbbit

**Comment by qwertyy-dev** [comment]
> Please decide @qwertyy-dev @mariocraft987 @BwnnyRxbbit

footer and settings.
- it avoids confusion (if a language option wasn't in settings, people would be very confused)
- it provides an easy-to-access option without even leaving the page their on
- when accounts are made in the future, settings will be hosted on the server rather than in localstorage, for fluidity across devices. but, this would require people to create an account before changing settings, which people who can't even read the language will have no idea how to do!

**Comment by BwnnyRxbbit** [comment]
> Please decide @qwertyy-dev @mariocraft987 @BwnnyRxbbit

I'm fine with anything

**Comment by Bashamega** [comment]
Well I am going to do both. if you don't like it comment it out of the footer
